
language: elixir
elixir:
  - 1.7.4
  - 1.8.2
  - 1.9.1
sudo: false # to use faster container based build environment
notifications:
  recipients:
    - howardbm@live.se
otp_release:
  - 20.3
  - 21.3
  - 22.0

# Dialyzer has some problems with these versions in travis
# Possibly related to: https://elixirforum.com/t/which-version-of-elixir-otp-erlang-can-we-use-with-dialyzer/17946/8
# and some new commits recently but I am not entirely convinced...
jobs:
  exclude:
  - elixir: 1.7.4
    otp_release: 21.3
  - elixir: 1.7.4
    otp_release: 22.0

env:
  - MIX_ENV=test
script:
  - mix do local.hex --force
  - mix deps.get
  - mix compile
  - travis_retry mix coveralls.travis
  - mix dialyzer --halt-exit-status
