
language: elixir
elixir:
  - 1.7.4
  - 1.8.2
  - 1.9.1
sudo: false # to use faster container based build environment
notifications:
  recipients:
    - howardbm@live.se
otp_release:
  - 20.3
  - 21.3
  - 22.0
env:
  - MIX_ENV=test
script:
  - mix do local.hex --force
  - mix deps.get
  - mix compile
  - travis_retry mix coveralls.travis
  - mix dialyzer --halt-exit-status
