
language: elixir
elixir:
  - 1.7.3
  - 1.8.2
sudo: false # to use faster container based build environment
notifications:
  recipients:
    - howardbm@live.se
otp_release:
  - 19.2
  - 20.3
  - 21.3
  - 22.0
env:
  - MIX_ENV=test
before_script:
  - export PLT_FILENAME=elixir-${TRAVIS_ELIXIR_VERSION}_${TRAVIS_OTP_RELEASE}.plt
  - export PLT_LOCATION=/home/travis/$PLT_FILENAME
  - $(wget -q -O $PLT_LOCATION https://raw.github.com/danielberkompas/travis_elixir_plts/master/$PLT_FILENAME) || unset PLT_LOCATION; return 0
script:
  - mix do local.hex --force
  - mix deps.get
  - mix compile
  - travis_retry mix coveralls.travis
  - mix dialyzer --halt-exit-status
matrix:
  exclude:
  - otp_release: 19.2
    elixir: 1.8.2
